global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'windows-exporter'
    static_configs:
      - targets: ['host.docker.internal:9182']

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
